// examples/vue/src/App.vue
<script setup lang="ts">
import { OverlayScrollbarsComponent } from 'overlayscrollbars-vue';
import type { PartialOptions } from 'overlayscrollbars';

const options: PartialOptions = {
  scrollbars: {
    theme: 'os-theme-light',
  },
};
</script>

<template>
  <a href="https://www.npmjs.com/package/overlayscrollbars-vue" target="_blank">
    <h1>OverlayScrollbars Vue</h1>
  </a>
  <OverlayScrollbarsComponent
    class="overlayscrollbars-vue"
    style="height: 222px; width: 222px"
    :options="options"
    defer
  >
    <div class="logo">
      <img alt="Vue logo" src="logo.svg" width="333" height="333" />
    </div>
  </OverlayScrollbarsComponent>
</template>

// examples/react/src/App.tsx
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';

const App = () => {
  return (
    <>
      <a href="https://www.npmjs.com/package/overlayscrollbars-react" target="_blank">
        <h1>OverlayScrollbars React</h1>
      </a>
      <OverlayScrollbarsComponent
        className="overlayscrollbars-react"
        style={{ width: '222px', height: '222px' }}
        options={{ scrollbars: { theme: 'os-theme-light' } }}
        defer
      >
        <div className="logo">
          <img alt="React logo" src="logo.svg" width="333" height="333" />
        </div>
      </OverlayScrollbarsComponent>
    </>
  );
};

export default App;
