// packages/overlayscrollbars-react/example/src/index.tsx
import 'overlayscrollbars/css/OverlayScrollbars.css'
import './index.css';
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import * as serviceWorker from './serviceWorker';
import OverlayScrollbars from 'overlayscrollbars';

ReactDOM.render(<App />, document.getElementById('root'));
serviceWorker.unregister();

OverlayScrollbars(document.body, {
    nativeScrollbarsOverlaid: {
        initialize: false
    }
});

// examples/solid/src/index.tsx
/* @refresh reload */
import 'overlayscrollbars/overlayscrollbars.css';
import { OverlayScrollbars, ClickScrollPlugin } from 'overlayscrollbars';
import { render } from 'solid-js/web';

import './index.css';
import App from './App';

OverlayScrollbars.plugin(ClickScrollPlugin);

render(() => <App />, document.getElementById('root') as HTMLElement);
