// packages/overlayscrollbars-react/example/src/App.tsx
import './App.css';
import React, { RefObject } from 'react';
import OverlayScrollbars from 'overlayscrollbars';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';

export interface AppState {
    componentContent: string;
    osComponentOptions: OverlayScrollbars.Options;
}

export default class App extends React.Component<any, AppState> {
    framework: string = 'React';
    componentClass: string = 'OverlayScrollbarsComponent';
    loremIpsumLong: string = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.';
    loremIpsumMedium: string = 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.';
    loremIpsumShort: string = 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio.';
    osComponentRef1: RefObject<OverlayScrollbarsComponent>;
    osComponentRef2: RefObject<OverlayScrollbarsComponent>;

    constructor(props: any) {
        super(props);
        this.osComponentRef1 = React.createRef<OverlayScrollbarsComponent>();
        this.osComponentRef2 = React.createRef<OverlayScrollbarsComponent>();
        this.state = {
            componentContent: 'Lorem Ipsum',
            osComponentOptions: {
                resize: 'both',
                paddingAbsolute: true,
                scrollbars: {
                    autoHide: 'never'
                }
            }
        };
    }

    componentDidMount() {
        console.log(`${this.componentClass} (1)`);
        console.log(this.osComponentRef1.current);

        console.log(`${this.componentClass} (2)`);
        console.log(this.osComponentRef2.current);
    }

    onBtnScrollRandom(event: React.MouseEvent<HTMLButtonElement, MouseEvent>, refArray: Array<RefObject<OverlayScrollbarsComponent>>) {
        if (refArray) {
            for (let i = 0; i < refArray.length; i++) {
                if (refArray[i] && refArray[i].current) {
                    let osInstance = refArray[i].current!.osInstance();
                    if (osInstance) {
                        osInstance.scrollStop().scroll({
                            x: Math.floor((Math.random() * osInstance.scroll().max.x) + 0),
                            y: Math.floor((Math.random() * osInstance.scroll().max.y) + 0)
                        }, 1000, 'easeOutElastic');
                    }
                }
            }
        }
    }

    onBtnChangeOptions() {
        this.setState({
            osComponentOptions: {
                resize: this.state.osComponentOptions.resize === 'both' ? 'none' : 'both',
                scrollbars: {
                    autoHide: this.state.osComponentOptions.scrollbars!.autoHide === 'never' ? 'scroll' : 'never',
                }
            }
        });
    }

    onBtnChangeContent() {
        let loremIpsums = [this.loremIpsumLong, this.loremIpsumMedium, this.loremIpsumShort];
        let random = Math.floor(Math.random() * loremIpsums.length);
        this.setState({
            componentContent: this.state.componentContent + "\r\n" + loremIpsums[random]
        });
    }

    onBtnLog() {
        console.log(`== ${this.componentClass} (1) ==`);
        console.log("Instance:");
        console.log(this.osComponentRef1.current!.osInstance());
        console.log("Target:");
        console.log(this.osComponentRef1.current!.osTarget());
        console.log("");
        console.log(`== ${this.componentClass} (2) ==`);
        console.log("Instance:");
        console.log(this.osComponentRef2.current!.osInstance());
        console.log("Target:");
        console.log(this.osComponentRef2.current!.osTarget());
    }

    render() {
        return (
            <div className="App">
                <div className="header">
                    <code>
                        <span className="code-keyword">import</span>
                        <span className="code-char">{' { '}</span>
                        <span className="code-variable">OverlayScrollbarsComponent</span>
                        <span className="code-char">{' } '}</span>
                        <span className="code-keyword">from</span>
                        <span className="code-string">{" 'overlayscrollbars-react'"}</span>
                        <span className="code-char">;</span>
                    </code>
                </div>
                <div className="content">
                    <div className="content-section skew">
                        <div className="content-section-content content-section-content-framework">
                            <span className="framework-logo"></span>
                            <span>+</span>
                            <span className="os-logo"></span>
                        </div>
                    </div>
                    <div className="content-section">
                        <div className="content-section-title">
                            <h2>Component</h2>
                            <table>
                                <tbody>
                                    <tr>
                                        <td><span>Class:</span></td>
                                        <td><span>{this.componentClass}</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>Description:</span></td>
                                        <td>OverlayScrollbars as a {this.framework}-Component.</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div className="content-section-content">

                            <OverlayScrollbarsComponent ref={this.osComponentRef1}
                                options={this.state.osComponentOptions}
                                style={{ maxHeight: '350px' }}
                                className={`custom-class-name-test ${this.framework}`}
                            >
                                <div className="bonus-content">
                                    {this.state.componentContent}
                                </div>
                                {this.loremIpsumShort}
                                <OverlayScrollbarsComponent ref={this.osComponentRef2}
                                    options={this.state.osComponentOptions}
                                    style={{ maxHeight: '150px' }}
                                    className="custom-class-name-test"
                                >
                                    <div className="bonus-content">
                                        {this.state.componentContent}
                                    </div>
                                    {this.loremIpsumLong}
                                    <br />
                                    <br />
                                    {this.loremIpsumShort}
                                </OverlayScrollbarsComponent>
                                {this.loremIpsumMedium}
                                <br />
                                <br />
                                {this.loremIpsumShort}
                                <br />
                                <br />
                                {this.loremIpsumLong}
                            </OverlayScrollbarsComponent>

                            <div className="buttons">
                                <button onClick={(event) => { this.onBtnScrollRandom.call(this, event, [this.osComponentRef1, this.osComponentRef2]) }}>Scroll</button>
                                <button onClick={() => { this.onBtnChangeOptions.call(this) }}>Change Options</button>
                                <button onClick={() => { this.onBtnChangeContent.call(this) }}>Change Content</button>
                                <button onClick={() => { this.onBtnLog.call(this) }}>Log</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

// packages/overlayscrollbars-ngx/example/src/app/app.component.ts
import { Component, ViewChild, ElementRef, Input } from '@angular/core';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-ngx';
import OverlayScrollbars from 'overlayscrollbars';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    framework: string = 'Angular';
    componentClass: string = 'OverlayScrollbarsComponent';
    loremIpsumLong: string = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.';
    loremIpsumMedium: string = 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.';
    loremIpsumShort: string = 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio.';
    componentContent: string = 'Lorem Ipsum';
    osComponentOptions: OverlayScrollbars.Options = {
        resize: 'both',
        paddingAbsolute: true,
        scrollbars: {
            autoHide: 'never'
        }
    };
    @ViewChild('osComponentRef1', { read: OverlayScrollbarsComponent })
    osComponentRef1: OverlayScrollbarsComponent;
    @ViewChild('osComponentRef2', { read: OverlayScrollbarsComponent })
    osComponentRef2: OverlayScrollbarsComponent;

    ngAfterViewInit() {
        console.log(`${this.componentClass} (1)`);
        console.log(this.osComponentRef1)

        console.log(`${this.componentClass} (2)`);
        console.log(this.osComponentRef2);
    }

    onBtnScrollRandom(event: any, refArray: ReadonlyArray<OverlayScrollbarsComponent>) {
        if (refArray) {
            for (let i = 0; i < refArray.length; i++) {
                if (refArray[i]) {
                    let osInstance = refArray[i].osInstance();
                    osInstance.scrollStop().scroll({
                        x: Math.floor((Math.random() * osInstance.scroll().max.x) + 0),
                        y: Math.floor((Math.random() * osInstance.scroll().max.y) + 0)
                    }, 1000, 'easeOutElastic');
                }
            }
        }
    }

    onBtnChangeOptions(event) {
        this.osComponentOptions = {
            resize: this.osComponentOptions.resize === 'both' ? 'none' : 'both',
            scrollbars: {
                autoHide: this.osComponentOptions.scrollbars.autoHide === 'never' ? 'scroll' : 'never',
            }
        }
    }

    onBtnChangeContent(event) {
        let loremIpsums = [this.loremIpsumLong, this.loremIpsumMedium, this.loremIpsumShort];
        let random = Math.floor(Math.random() * loremIpsums.length);
        this.componentContent = this.componentContent + '\r\n' + loremIpsums[random]
    }

    onBtnLog(event) {
        console.log(`== ${this.componentClass} (1) ==`);
        console.log('Ref:');
        console.log(this.osComponentRef1);
        console.log('Instance:');
        console.log(this.osComponentRef1.osInstance());
        console.log('Target:');
        console.log(this.osComponentRef1.osTarget());
        console.log('');
        console.log(`== ${this.componentClass} (2) ==`);
        console.log('Ref:');
        console.log(this.osComponentRef2);
        console.log('Instance:');
        console.log(this.osComponentRef2.osInstance());
        console.log('Target:');
        console.log(this.osComponentRef2.osTarget());
    }
}

<div class="header">
    <code>
        <span class="code-keyword">import</span>
        <span class="code-char">{{ ' { ' }}</span>
        <span class="code-variable">OverlayScrollbarsComponent</span>
        <span class="code-char">{{ ' } ' }}</span>
        <span class="code-keyword">from</span>
        <span class="code-string">{{ " 'overlayscrollbars-ngx'" }}</span>
        <span class="code-char">;</span>
    </code>
</div>
<div class="content">
    <div class="content-section skew">
        <div class="content-section-content content-section-content-framework">
            <span class="framework-logo"></span>
            <span>+</span>
            <span class="os-logo"></span>
        </div>
    </div>
    <div class="content-section">
        <div class="content-section-title">
            <h2>Component</h2>
            <table>
                <tbody>
                    <tr>
                        <td>
                            <span>Class:</span>
                        </td>
                        <td>
                            <span>{{ componentClass }}</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Description:</span>
                        </td>
                        <td>OverlayScrollbars as a {{ framework }}-Component.</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="content-section-content">

            <overlay-scrollbars #osComponentRef1 [options]="osComponentOptions" [ngStyle]="{ maxHeight:'350px' }"
                [ngClass]="['custom-class-name-test', framework]">
                <div class="bonus-content">{{ componentContent }}</div>
                {{ loremIpsumShort }}
                <overlay-scrollbars #osComponentRef2 [options]="osComponentOptions" [ngStyle]="{ maxHeight:'150px' }"
                    [ngClass]="['custom-class-name-test']">
                    <div class="bonus-content">{{ componentContent }}</div>
                    {{ loremIpsumLong }}
                    <br />
                    <br /> {{ loremIpsumShort }}
                </overlay-scrollbars>
                {{ loremIpsumMedium }}
                <br />
                <br /> {{ loremIpsumShort }}
                <br />
                <br /> {{ loremIpsumLong }}
            </overlay-scrollbars>

            <div class="buttons">
                <button (click)="onBtnScrollRandom($event, [ osComponentRef1, osComponentRef2 ])">Scroll</button>
                <button (click)="onBtnChangeOptions($event)">Change Options</button>
                <button (click)="onBtnChangeContent($event)">Change Content</button>
                <button (click)="onBtnLog($event)">Log</button>
            </div>
        </div>
    </div>
</div>
