// packages/overlayscrollbars-vue/src/OverlayScrollbarsComponent.vue
<script setup lang="ts">
import { ref, unref, shallowRef, toRefs, watch, watchPostEffect, onUnmounted } from 'vue';
import { useOverlayScrollbars } from './useOverlayScrollbars';
import type {
  OverlayScrollbarsComponentProps,
  OverlayScrollbarsComponentRef,
} from './OverlayScrollbarsComponent.types';
import type { PropType } from 'vue';
import type { EventListeners, EventListenerArgs } from 'overlayscrollbars';

type EmitEventsMap = {
  [N in keyof EventListenerArgs]: `os${Capitalize<N>}`;
};

const emitEvents: EmitEventsMap = {
  initialized: 'osInitialized',
  updated: 'osUpdated',
  destroyed: 'osDestroyed',
  scroll: 'osScroll',
};
const props = defineProps({
  element: {
    type: String as PropType<OverlayScrollbarsComponentProps['element']>,
    default: 'div',
  },
  options: { type: Object as PropType<OverlayScrollbarsComponentProps['options']> },
  events: { type: Object as PropType<OverlayScrollbarsComponentProps['events']> },
});
const emits = defineEmits<{
  (name: 'osInitialized', ...args: EventListenerArgs['initialized']): void;
  (name: 'osUpdated', ...args: EventListenerArgs['updated']): void;
  (name: 'osDestroyed', ...args: EventListenerArgs['destroyed']): void;
  (name: 'osScroll', ...args: EventListenerArgs['scroll']): void;
}>();

const elementRef = shallowRef<HTMLElement | null>(null);
const slotRef = shallowRef<HTMLElement | null>(null);
const combinedEvents = ref<EventListeners>();
const { element, options, events } = toRefs(props);
const [initialize, instance] = useOverlayScrollbars({ options, events: combinedEvents });
const exposed: OverlayScrollbarsComponentRef = {
  instance,
  element: () => elementRef.value,
};

defineExpose(exposed);

onUnmounted(() => instance()?.destroy());

watchPostEffect((onCleanup) => {
  const { value: elm } = elementRef;
  const { value: slotElm } = slotRef;

  if (elm && slotElm) {
    const osInstance = initialize({
      target: elm,
      elements: {
        viewport: slotElm,
        content: slotElm,
      },
    });
    onCleanup(() => osInstance.destroy());
  }
});

watch(
  () => unref(events),
  (rawCurrEvents) => {
    const currEvents = rawCurrEvents || {};
    combinedEvents.value = (
      Object.keys(emitEvents) as (keyof EventListeners)[]
    ).reduce<EventListeners>(<N extends keyof EventListeners>(obj: EventListeners, name: N) => {
      const eventListener = currEvents[name];
      obj[name] = [
        (...args: EventListenerArgs[N]) =>
          emits(
            emitEvents[name],
            // @ts-ignore
            ...args
          ),
        ...(Array.isArray(eventListener) ? eventListener : [eventListener]).filter(Boolean),
      ];
      return obj;
    }, {});
  },
  { deep: true, immediate: true }
);
</script>

<template>
  <component :is="element" ref="elementRef" data-overlayscrollbars="">
    <div ref="slotRef">
      <slot></slot>
    </div>
  </component>
</template>

// packages/overlayscrollbars-svelte/src/OverlayScrollbarsComponent.svelte
<script lang="ts">
  import { onMount, afterUpdate, createEventDispatcher } from 'svelte';
  import { OverlayScrollbars } from 'overlayscrollbars';
  import type { EventListeners, EventListenerArgs } from 'overlayscrollbars';
  import type { OverlayScrollbarsComponentProps$, OverlayScrollbarsComponentRef$ } from './OverlayScrollbarsComponent.types';

  type EmitEventsMap = {
    [N in keyof EventListenerArgs]: `os${Capitalize<N>}`;
  };

  export let element: OverlayScrollbarsComponentProps$["element"] = 'div';
  export let options: OverlayScrollbarsComponentProps$["options"] = undefined;
  export let events: OverlayScrollbarsComponentProps$["events"] = undefined;

  let instance: OverlayScrollbars | null = null;
  let elementRef: HTMLElement | null = null;
  let slotRef: HTMLElement | null = null;
  let combinedEvents: OverlayScrollbarsComponentProps$["events"] = undefined;
  let prevElement: string | undefined;

  const initialize = () => {
    instance?.destroy();
    instance = OverlayScrollbars(
      { 
        target: elementRef!, 
        elements: {
          viewport: slotRef,
          content: slotRef
        } 
      }, 
      options || {}, 
      combinedEvents || {}
    );
    prevElement = element;
    return () => instance?.destroy();
  };
  const dispatchEvents: EmitEventsMap = {
    initialized: 'osInitialized',
    updated: 'osUpdated',
    destroyed: 'osDestroyed',
    scroll: 'osScroll',
  };
  const dispatchEvent = createEventDispatcher<{
    osInitialized: EventListenerArgs["initialized"];
    osUpdated: EventListenerArgs["updated"];
    osDestroyed: EventListenerArgs["destroyed"];
    osScroll: EventListenerArgs["scroll"];
  }>();

  export const osInstance: OverlayScrollbarsComponentRef$["osInstance"] = () => instance;
  export const getElement: OverlayScrollbarsComponentRef$["getElement"] = () => elementRef;

  onMount(initialize);

  afterUpdate(() => {
    if (prevElement !== element) {
      initialize();
    }
  });
  
  $: {
    const currEvents = events || {};
    combinedEvents = (
      Object.keys(dispatchEvents) as (keyof EventListeners)[]
    ).reduce<EventListeners>(<N extends keyof EventListeners>(obj: EventListeners, name: N) => {
      const eventListener = currEvents[name];
      obj[name] = [
        (...args: EventListenerArgs[N]) =>
          dispatchEvent(
            dispatchEvents[name],
            // @ts-ignore
            args
          ),
        ...(Array.isArray(eventListener) ? eventListener : [eventListener]).filter(Boolean),
      ];
      return obj;
    }, {});
  }

  $: { 
    if (OverlayScrollbars.valid(instance)) {
      instance.options(options || {}, true);
    }
  }

  $: { 
    if (OverlayScrollbars.valid(instance)) {
      instance.on(
        /* c8 ignore next */
        combinedEvents || {}, 
        true
      );
    }
  }
</script>

<svelte:element data-overlayscrollbars-initialize="" this={element} bind:this={elementRef} {...$$restProps}>
  <div bind:this={slotRef}>
    <slot></slot>
  </div>
</svelte:element>
